services:
  sae5db:
    container_name: sae5db
    image: postgres:18.0
    volumes:
      - ./data/postgres:/var/lib/postgresql/18/docker
    ports:
      - 0.0.0.0:${PGDB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - sae5

  sae5pgadmin:
    image: dpage/pgadmin4
    container_name: sae5pgadmin
    restart: always
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
      - ./data/pgadmin_logs:/var/log/pgadmin
    ports:
      - 0.0.0.0:${PGADMIN_PORT}:80
    environment:
      VIRTUAL_HOST: localhost
      PGADMIN_DEFAULT_EMAIL: ${EQUIPE}@dbadmin-sae.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: true
    networks:
      - sae5
    depends_on:
      - sae5db

networks:
  sae5:
